storage_account_name = "tfstalabscastillo"
container_name       = "tfstate"
key                  = "pro/aks_pro.tfstate"
resource_group_name  = "aks-pro"
access_key           = "dU7trMdxJfHuUA2ZUX6IeXx2IG7bhi63xWd2iYXRLilLttD9qmyEwgB9lez0G7RRjOuHNMKCdk2m58rVKlDJ7g=="
